import { IChatBotTheme } from "@/types/chatbot";

export interface ThemePreset {
    name: string;
    displayName: string;
    description: string;
    primaryColor: string;
    secondaryColor: string;
    theme: IChatBotTheme;
}

/**
 * Chatbot Theme Presets
 *
 * Professionally designed color palettes with WCAG AA compliant contrast ratios (4.5:1 for text).
 * Each preset includes comprehensive light and dark mode configurations with all 32 color properties.
 * Strategic use of transparency (alpha channel) for modern, polished UI effects.
 */
export const CHATBOT_THEME_PRESETS: ThemePreset[] = [
    // 1. PLATFORM MATCHING - Exactly matches the main platform UI
    {
        name: "platform",
        displayName: "Platform",
        description: "Matches Platform UI",
        primaryColor: "#0a766c",
        secondaryColor: "#f8fafc",
        theme: {
            light: {
                bg_color: "#ffffff",
                accent_color: "#0a766c",
                ai_bubble_color: "#f8fafc",
                ai_bubble_text_color: "#0f172a",
                ai_bubble_border_color: "#e2e8f0e6",
                user_bubble_color: "#0a766c",
                user_bubble_text_color: "#ffffff",
                user_bubble_border_color: "#0a766c",
                text_field_color: "#fffffffa",
                text_field_foreground: "#0f172a",
                text_field_icon_color: "#64748b",
                footer_bg_color: "#f8fafcf5",
                header_color: "#fffffffa",
                header_text_color: "#0f172a",
                header_separator_color: "#e2e8f0cc",
                ai_profile_bg_color: "#0a766c",
                user_profile_bg_color: "#0a766c",
                header_icon_color: "#0f172ad9",
                send_btn_color: "#0a766c",
                send_btn_icon_color: "#ffffff",
                input_placeholder_color: "#94a3b8cc",
                timestamp_color: "#94a3b8b3",
                search_highlight_color: "#fef08acc",
                loading_indicator_color: "#0a766c",
                footer_text_color: "#94a3b8b3",
                success_color: "#22c55e",
                header_logo_border_color: "#e2e8f0e6",
                header_logo_bg_color: "#ffffff1a",
                welcome_text_color: "#64748bd9",
                suggested_prompt_title_color: "#0f172a",
                suggested_prompt_desc_color: "#64748bcc",
                suggested_prompt_icon_color: "#64748bb3",
            },
            dark: {
                bg_color: "#171717",
                accent_color: "#14b8a6",
                ai_bubble_color: "#21212199",
                ai_bubble_text_color: "#f8fafc",
                ai_bubble_border_color: "#33415566",
                user_bubble_color: "#14b8a6",
                user_bubble_text_color: "#0f172a",
                user_bubble_border_color: "#14b8a6",
                text_field_color: "#212121f5",
                text_field_foreground: "#f8fafc",
                text_field_icon_color: "#94a3b8",
                footer_bg_color: "#171717f5",
                header_color: "#171717fa",
                header_text_color: "#f8fafc",
                header_separator_color: "#33415533",
                ai_profile_bg_color: "#14b8a6",
                user_profile_bg_color: "#14b8a6",
                header_icon_color: "#f8fafce6",
                send_btn_color: "#14b8a6",
                send_btn_icon_color: "#0f172a",
                input_placeholder_color: "#64748bb3",
                timestamp_color: "#64748b99",
                search_highlight_color: "#ca8a04b3",
                loading_indicator_color: "#14b8a6",
                footer_text_color: "#64748b99",
                success_color: "#4ade80",
                header_logo_border_color: "#33415566",
                header_logo_bg_color: "#17171733",
                welcome_text_color: "#94a3b8cc",
                suggested_prompt_title_color: "#f8fafc",
                suggested_prompt_desc_color: "#94a3b8b3",
                suggested_prompt_icon_color: "#94a3b899",
            },
            msg_bubble_radius: 12,
            input_radius: 12,
            header_logo_radius: 8,
            header_logo_width: 36,
            header_logo_height: 36,
            header_logo_border_width: 0,
            shadow_intensity: "sm",
            loading_animation_style: "dot",
            show_header_separator: true,
        },
    },

    // 2. OCEAN BLUE - Deep blue with excellent readability
    {
        name: "ocean",
        displayName: "Ocean",
        description: "Deep Blue Waters",
        primaryColor: "#0369a1",
        secondaryColor: "#e0f2fe",
        theme: {
            light: {
                bg_color: "#f0f9ff",
                accent_color: "#0369a1",
                ai_bubble_color: "#e0f2fef5",
                ai_bubble_text_color: "#075985",
                ai_bubble_border_color: "#bae6fde6",
                user_bubble_color: "#0369a1",
                user_bubble_text_color: "#ffffff",
                user_bubble_border_color: "#0369a1",
                text_field_color: "#fffffff5",
                text_field_foreground: "#075985",
                text_field_icon_color: "#0284c7",
                footer_bg_color: "#f0f9fff2",
                header_color: "#f0f9fffa",
                header_text_color: "#075985",
                header_separator_color: "#bae6fdcc",
                ai_profile_bg_color: "#0369a1",
                user_profile_bg_color: "#0369a1",
                header_icon_color: "#075985d9",
                send_btn_color: "#0369a1",
                send_btn_icon_color: "#ffffff",
                input_placeholder_color: "#0284c7cc",
                timestamp_color: "#0284c7b3",
                search_highlight_color: "#fef08acc",
                loading_indicator_color: "#0369a1",
                footer_text_color: "#0284c7b3",
                success_color: "#22c55e",
                header_logo_border_color: "#bae6fde6",
                header_logo_bg_color: "#f0f9ff26",
                welcome_text_color: "#0284c7d9",
                suggested_prompt_title_color: "#075985",
                suggested_prompt_desc_color: "#0284c7cc",
                suggested_prompt_icon_color: "#0284c7b3",
            },
            dark: {
                bg_color: "#0c1e2e",
                accent_color: "#38bdf8",
                ai_bubble_color: "#164e6399",
                ai_bubble_text_color: "#e0f2fe",
                ai_bubble_border_color: "#0e749066",
                user_bubble_color: "#38bdf8",
                user_bubble_text_color: "#0c1e2e",
                user_bubble_border_color: "#38bdf8",
                text_field_color: "#164e63f5",
                text_field_foreground: "#e0f2fe",
                text_field_icon_color: "#7dd3fc",
                footer_bg_color: "#0c1e2ef5",
                header_color: "#0c1e2efa",
                header_text_color: "#e0f2fe",
                header_separator_color: "#0e749033",
                ai_profile_bg_color: "#38bdf8",
                user_profile_bg_color: "#38bdf8",
                header_icon_color: "#e0f2fee6",
                send_btn_color: "#38bdf8",
                send_btn_icon_color: "#0c1e2e",
                input_placeholder_color: "#7dd3fcb3",
                timestamp_color: "#7dd3fc99",
                search_highlight_color: "#fbbf24b3",
                loading_indicator_color: "#38bdf8",
                footer_text_color: "#7dd3fc99",
                success_color: "#4ade80",
                header_logo_border_color: "#0e749066",
                header_logo_bg_color: "#0c1e2e33",
                welcome_text_color: "#7dd3fccc",
                suggested_prompt_title_color: "#e0f2fe",
                suggested_prompt_desc_color: "#7dd3fcb3",
                suggested_prompt_icon_color: "#7dd3fc99",
            },
            msg_bubble_radius: 16,
            input_radius: 12,
            header_logo_radius: 12,
            header_logo_width: 40,
            header_logo_height: 40,
            header_logo_border_width: 0,
            shadow_intensity: "md",
            loading_animation_style: "wave",
            show_header_separator: true,
        },
    },

    // 3. SUNSET AMBER - Warm, inviting orange tones
    {
        name: "sunset",
        displayName: "Sunset",
        description: "Warm Golden Hour",
        primaryColor: "#ea580c",
        secondaryColor: "#ffedd5",
        theme: {
            light: {
                bg_color: "#fff7ed",
                accent_color: "#ea580c",
                ai_bubble_color: "#ffedd5f5",
                ai_bubble_text_color: "#9a3412",
                ai_bubble_border_color: "#fed7aae6",
                user_bubble_color: "#ea580c",
                user_bubble_text_color: "#ffffff",
                user_bubble_border_color: "#ea580c",
                text_field_color: "#fffffff5",
                text_field_foreground: "#9a3412",
                text_field_icon_color: "#f97316",
                footer_bg_color: "#fff7edf2",
                header_color: "#fff7edfa",
                header_text_color: "#9a3412",
                header_separator_color: "#fed7aacc",
                ai_profile_bg_color: "#ea580c",
                user_profile_bg_color: "#ea580c",
                header_icon_color: "#9a3412d9",
                send_btn_color: "#ea580c",
                send_btn_icon_color: "#ffffff",
                input_placeholder_color: "#f97316cc",
                timestamp_color: "#f97316b3",
                search_highlight_color: "#fef08acc",
                loading_indicator_color: "#ea580c",
                footer_text_color: "#f97316b3",
                success_color: "#22c55e",
                header_logo_border_color: "#fed7aae6",
                header_logo_bg_color: "#fff7ed26",
                welcome_text_color: "#f97316d9",
                suggested_prompt_title_color: "#9a3412",
                suggested_prompt_desc_color: "#f97316cc",
                suggested_prompt_icon_color: "#f97316b3",
            },
            dark: {
                bg_color: "#431407",
                accent_color: "#fb923c",
                ai_bubble_color: "#7c2d1299",
                ai_bubble_text_color: "#ffedd5",
                ai_bubble_border_color: "#9a341266",
                user_bubble_color: "#fb923c",
                user_bubble_text_color: "#431407",
                user_bubble_border_color: "#fb923c",
                text_field_color: "#7c2d12f5",
                text_field_foreground: "#ffedd5",
                text_field_icon_color: "#fdba74",
                footer_bg_color: "#431407f5",
                header_color: "#431407fa",
                header_text_color: "#ffedd5",
                header_separator_color: "#9a341233",
                ai_profile_bg_color: "#fb923c",
                user_profile_bg_color: "#fb923c",
                header_icon_color: "#ffedd5e6",
                send_btn_color: "#fb923c",
                send_btn_icon_color: "#431407",
                input_placeholder_color: "#fdba74b3",
                timestamp_color: "#fdba7499",
                search_highlight_color: "#fef08ab3",
                loading_indicator_color: "#fb923c",
                footer_text_color: "#fdba7499",
                success_color: "#4ade80",
                header_logo_border_color: "#9a341266",
                header_logo_bg_color: "#43140733",
                welcome_text_color: "#fdba74cc",
                suggested_prompt_title_color: "#ffedd5",
                suggested_prompt_desc_color: "#fdba74b3",
                suggested_prompt_icon_color: "#fdba7499",
            },
            msg_bubble_radius: 14,
            input_radius: 14,
            header_logo_radius: 10,
            header_logo_width: 38,
            header_logo_height: 38,
            header_logo_border_width: 0,
            shadow_intensity: "md",
            loading_animation_style: "dot",
            show_header_separator: true,
        },
    },

    // 4. FOREST GREEN - Nature-inspired, calming greens
    {
        name: "forest",
        displayName: "Forest",
        description: "Natural Green",
        primaryColor: "#15803d",
        secondaryColor: "#dcfce7",
        theme: {
            light: {
                bg_color: "#f0fdf4",
                accent_color: "#15803d",
                ai_bubble_color: "#dcfce7f5",
                ai_bubble_text_color: "#14532d",
                ai_bubble_border_color: "#bbf7d0e6",
                user_bubble_color: "#15803d",
                user_bubble_text_color: "#ffffff",
                user_bubble_border_color: "#15803d",
                text_field_color: "#fffffff5",
                text_field_foreground: "#14532d",
                text_field_icon_color: "#16a34a",
                footer_bg_color: "#f0fdf4f2",
                header_color: "#f0fdf4fa",
                header_text_color: "#14532d",
                header_separator_color: "#bbf7d0cc",
                ai_profile_bg_color: "#15803d",
                user_profile_bg_color: "#15803d",
                header_icon_color: "#14532dd9",
                send_btn_color: "#15803d",
                send_btn_icon_color: "#ffffff",
                input_placeholder_color: "#16a34acc",
                timestamp_color: "#16a34ab3",
                search_highlight_color: "#fef08acc",
                loading_indicator_color: "#15803d",
                footer_text_color: "#16a34ab3",
                success_color: "#22c55e",
                header_logo_border_color: "#bbf7d0e6",
                header_logo_bg_color: "#f0fdf426",
                welcome_text_color: "#16a34ad9",
                suggested_prompt_title_color: "#14532d",
                suggested_prompt_desc_color: "#16a34acc",
                suggested_prompt_icon_color: "#16a34ab3",
            },
            dark: {
                bg_color: "#052e16",
                accent_color: "#4ade80",
                ai_bubble_color: "#14532d99",
                ai_bubble_text_color: "#dcfce7",
                ai_bubble_border_color: "#16653466",
                user_bubble_color: "#4ade80",
                user_bubble_text_color: "#052e16",
                user_bubble_border_color: "#4ade80",
                text_field_color: "#14532df5",
                text_field_foreground: "#dcfce7",
                text_field_icon_color: "#86efac",
                footer_bg_color: "#052e16f5",
                header_color: "#052e16fa",
                header_text_color: "#dcfce7",
                header_separator_color: "#16653433",
                ai_profile_bg_color: "#4ade80",
                user_profile_bg_color: "#4ade80",
                header_icon_color: "#dcfce7e6",
                send_btn_color: "#4ade80",
                send_btn_icon_color: "#052e16",
                input_placeholder_color: "#86efacb3",
                timestamp_color: "#86efac99",
                search_highlight_color: "#fbbf24b3",
                loading_indicator_color: "#4ade80",
                footer_text_color: "#86efac99",
                success_color: "#4ade80",
                header_logo_border_color: "#16653466",
                header_logo_bg_color: "#052e1633",
                welcome_text_color: "#86efaccc",
                suggested_prompt_title_color: "#dcfce7",
                suggested_prompt_desc_color: "#86efacb3",
                suggested_prompt_icon_color: "#86efac99",
            },
            msg_bubble_radius: 12,
            input_radius: 12,
            header_logo_radius: 8,
            header_logo_width: 36,
            header_logo_height: 36,
            header_logo_border_width: 0,
            shadow_intensity: "sm",
            loading_animation_style: "circle",
            show_header_separator: true,
        },
    },

    // 5. ROYAL PURPLE - Elegant and sophisticated
    {
        name: "royal",
        displayName: "Royal",
        description: "Elegant Purple",
        primaryColor: "#7c3aed",
        secondaryColor: "#f5f3ff",
        theme: {
            light: {
                bg_color: "#faf5ff",
                accent_color: "#7c3aed",
                ai_bubble_color: "#f5f3fff5",
                ai_bubble_text_color: "#5b21b6",
                ai_bubble_border_color: "#ddd6fee6",
                user_bubble_color: "#7c3aed",
                user_bubble_text_color: "#ffffff",
                user_bubble_border_color: "#7c3aed",
                text_field_color: "#fffffff5",
                text_field_foreground: "#5b21b6",
                text_field_icon_color: "#8b5cf6",
                footer_bg_color: "#faf5fff2",
                header_color: "#faf5fffa",
                header_text_color: "#5b21b6",
                header_separator_color: "#ddd6fecc",
                ai_profile_bg_color: "#7c3aed",
                user_profile_bg_color: "#7c3aed",
                header_icon_color: "#5b21b6d9",
                send_btn_color: "#7c3aed",
                send_btn_icon_color: "#ffffff",
                input_placeholder_color: "#8b5cf6cc",
                timestamp_color: "#8b5cf6b3",
                search_highlight_color: "#fef08acc",
                loading_indicator_color: "#7c3aed",
                footer_text_color: "#8b5cf6b3",
                success_color: "#22c55e",
                header_logo_border_color: "#ddd6fee6",
                header_logo_bg_color: "#faf5ff26",
                welcome_text_color: "#8b5cf6d9",
                suggested_prompt_title_color: "#5b21b6",
                suggested_prompt_desc_color: "#8b5cf6cc",
                suggested_prompt_icon_color: "#8b5cf6b3",
            },
            dark: {
                bg_color: "#2e1065",
                accent_color: "#a78bfa",
                ai_bubble_color: "#4c1d9599",
                ai_bubble_text_color: "#f5f3ff",
                ai_bubble_border_color: "#5b21b666",
                user_bubble_color: "#a78bfa",
                user_bubble_text_color: "#2e1065",
                user_bubble_border_color: "#a78bfa",
                text_field_color: "#4c1d95f5",
                text_field_foreground: "#f5f3ff",
                text_field_icon_color: "#c4b5fd",
                footer_bg_color: "#2e1065f5",
                header_color: "#2e1065fa",
                header_text_color: "#f5f3ff",
                header_separator_color: "#5b21b633",
                ai_profile_bg_color: "#a78bfa",
                user_profile_bg_color: "#a78bfa",
                header_icon_color: "#f5f3ffe6",
                send_btn_color: "#a78bfa",
                send_btn_icon_color: "#2e1065",
                input_placeholder_color: "#c4b5fdb3",
                timestamp_color: "#c4b5fd99",
                search_highlight_color: "#fbbf24b3",
                loading_indicator_color: "#a78bfa",
                footer_text_color: "#c4b5fd99",
                success_color: "#4ade80",
                header_logo_border_color: "#5b21b666",
                header_logo_bg_color: "#2e106533",
                welcome_text_color: "#c4b5fdcc",
                suggested_prompt_title_color: "#f5f3ff",
                suggested_prompt_desc_color: "#c4b5fdb3",
                suggested_prompt_icon_color: "#c4b5fd99",
            },
            msg_bubble_radius: 18,
            input_radius: 14,
            header_logo_radius: 12,
            header_logo_width: 42,
            header_logo_height: 42,
            header_logo_border_width: 2,
            shadow_intensity: "lg",
            loading_animation_style: "circle",
            show_header_separator: true,
        },
    },

    // 6. MIDNIGHT SLATE - Modern, professional grayscale
    {
        name: "midnight",
        displayName: "Midnight",
        description: "Modern Grayscale",
        primaryColor: "#475569",
        secondaryColor: "#f1f5f9",
        theme: {
            light: {
                bg_color: "#f8fafc",
                accent_color: "#475569",
                ai_bubble_color: "#f1f5f9f5",
                ai_bubble_text_color: "#1e293b",
                ai_bubble_border_color: "#cbd5e1e6",
                user_bubble_color: "#475569",
                user_bubble_text_color: "#ffffff",
                user_bubble_border_color: "#475569",
                text_field_color: "#fffffff5",
                text_field_foreground: "#1e293b",
                text_field_icon_color: "#64748b",
                footer_bg_color: "#f8fafcf2",
                header_color: "#f8fafcfa",
                header_text_color: "#1e293b",
                header_separator_color: "#cbd5e1cc",
                ai_profile_bg_color: "#475569",
                user_profile_bg_color: "#475569",
                header_icon_color: "#1e293bd9",
                send_btn_color: "#475569",
                send_btn_icon_color: "#ffffff",
                input_placeholder_color: "#94a3b8cc",
                timestamp_color: "#94a3b8b3",
                search_highlight_color: "#fef08acc",
                loading_indicator_color: "#475569",
                footer_text_color: "#94a3b8b3",
                success_color: "#22c55e",
                header_logo_border_color: "#cbd5e1e6",
                header_logo_bg_color: "#f8fafc26",
                welcome_text_color: "#64748bd9",
                suggested_prompt_title_color: "#1e293b",
                suggested_prompt_desc_color: "#64748bcc",
                suggested_prompt_icon_color: "#64748bb3",
            },
            dark: {
                bg_color: "#0f172a",
                accent_color: "#94a3b8",
                ai_bubble_color: "#1e293b99",
                ai_bubble_text_color: "#f1f5f9",
                ai_bubble_border_color: "#33415566",
                user_bubble_color: "#94a3b8",
                user_bubble_text_color: "#0f172a",
                user_bubble_border_color: "#94a3b8",
                text_field_color: "#1e293bf5",
                text_field_foreground: "#f1f5f9",
                text_field_icon_color: "#cbd5e1",
                footer_bg_color: "#0f172af5",
                header_color: "#0f172afa",
                header_text_color: "#f1f5f9",
                header_separator_color: "#33415533",
                ai_profile_bg_color: "#94a3b8",
                user_profile_bg_color: "#94a3b8",
                header_icon_color: "#f1f5f9e6",
                send_btn_color: "#94a3b8",
                send_btn_icon_color: "#0f172a",
                input_placeholder_color: "#cbd5e1b3",
                timestamp_color: "#cbd5e199",
                search_highlight_color: "#fbbf24b3",
                loading_indicator_color: "#94a3b8",
                footer_text_color: "#cbd5e199",
                success_color: "#4ade80",
                header_logo_border_color: "#33415566",
                header_logo_bg_color: "#0f172a33",
                welcome_text_color: "#cbd5e1cc",
                suggested_prompt_title_color: "#f1f5f9",
                suggested_prompt_desc_color: "#cbd5e1b3",
                suggested_prompt_icon_color: "#cbd5e199",
            },
            msg_bubble_radius: 10,
            input_radius: 10,
            header_logo_radius: 6,
            header_logo_width: 34,
            header_logo_height: 34,
            header_logo_border_width: 0,
            shadow_intensity: "sm",
            loading_animation_style: "dot",
            show_header_separator: true,
        },
    },
];

/**
 * Get a preset by name
 */
export function getPresetByName(name: string): ThemePreset | undefined {
    return CHATBOT_THEME_PRESETS.find(p => p.name.toLowerCase() === name.toLowerCase());
}

/**
 * Get the default preset
 */
export function getDefaultPreset(): ThemePreset | undefined {
    return CHATBOT_THEME_PRESETS[0];
}
