import { IChatBotTheme } from "@/types/chatbot";

// Helper to migrate legacy themes to the new nested structure
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const migrateTheme = (theme: any): IChatBotTheme | undefined => {
    if (!theme) return undefined;

    // Check if it's already in the new structure (has light and dark objects)
    if (theme.light && theme.dark) {
        return {
            light: {
                bg_color: theme.light.bg_color || "#ffffff",
                ai_bubble_color: theme.light.ai_bubble_color || "#ffffff",
                user_bubble_color: theme.light.user_bubble_color || "#0a766c",
                user_profile_bg_color: theme.light.user_profile_bg_color || "#0a766c",
                ai_profile_bg_color: theme.light.ai_profile_bg_color || "#0a766c",
                header_separator_color: theme.light.header_separator_color || "#e2e8f0",
                accent_color: theme.light.accent_color || "#0a766c",
                text_field_color: theme.light.text_field_color || "#ffffff",
                text_field_foreground: theme.light.text_field_foreground || "#0f172a",
                text_field_icon_color: theme.light.text_field_icon_color || theme.light.text_field_foreground || "#0f172a",
                footer_bg_color: theme.light.footer_bg_color || "#f8fafc",
                header_color: theme.light.header_color || "#ffffff",
                header_text_color: theme.light.header_text_color || "#0f172a",
                ai_bubble_text_color: theme.light.ai_bubble_text_color || "#0f172a",
                user_bubble_text_color: theme.light.user_bubble_text_color || "#ffffff",
                ai_bubble_border_color: theme.light.ai_bubble_border_color || "#e2e8f0",
                user_bubble_border_color: theme.light.user_bubble_border_color || "#e2e8f0",
                // New granular color properties with smart defaults
                header_icon_color: theme.light.header_icon_color || theme.light.header_text_color || "#0f172a",
                send_btn_color: theme.light.send_btn_color || theme.light.accent_color || "#0a766c",
                send_btn_icon_color: theme.light.send_btn_icon_color || "#ffffff",
                input_placeholder_color: theme.light.input_placeholder_color || "#94a3b8",
                timestamp_color: theme.light.timestamp_color || "#94a3b8",
                search_highlight_color: theme.light.search_highlight_color || "#fef08a",
                loading_indicator_color: theme.light.loading_indicator_color || theme.light.accent_color || "#0a766c",
                footer_text_color: theme.light.footer_text_color || "#94a3b8",
                success_color: theme.light.success_color || "#22c55e",
                header_logo_border_color: theme.light.header_logo_border_color || theme.light.ai_bubble_border_color || "#e2e8f0",
                header_logo_bg_color: theme.light.header_logo_bg_color || theme.light.bg_color || "#ffffff",
                welcome_text_color: theme.light.welcome_text_color || "#64748b",
                suggested_prompt_title_color: theme.light.suggested_prompt_title_color || "#0f172a",
                suggested_prompt_desc_color: theme.light.suggested_prompt_desc_color || "#64748b",
                suggested_prompt_icon_color: theme.light.suggested_prompt_icon_color || "#64748b",
            },
            dark: {
                bg_color: theme.dark.bg_color || "#020817",
                ai_bubble_color: theme.dark.ai_bubble_color || "#1e293b",
                user_bubble_color: theme.dark.user_bubble_color || "#0a766c",
                user_profile_bg_color: theme.dark.user_profile_bg_color || "#0a766c",
                ai_profile_bg_color: theme.dark.ai_profile_bg_color || "#0a766c",
                header_separator_color: theme.dark.header_separator_color || "#334155",
                accent_color: theme.dark.accent_color || "#0a766c",
                text_field_color: theme.dark.text_field_color || "#1e293b",
                text_field_foreground: theme.dark.text_field_foreground || "#e2e8f0",
                text_field_icon_color: theme.dark.text_field_icon_color || theme.dark.text_field_foreground || "#e2e8f0",
                footer_bg_color: theme.dark.footer_bg_color || "#0f172a",
                header_color: theme.dark.header_color || "#020817",
                header_text_color: theme.dark.header_text_color || "#e2e8f0",
                ai_bubble_text_color: theme.dark.ai_bubble_text_color || "#e2e8f0",
                user_bubble_text_color: theme.dark.user_bubble_text_color || "#ffffff",
                ai_bubble_border_color: theme.dark.ai_bubble_border_color || "#334155",
                user_bubble_border_color: theme.dark.user_bubble_border_color || "#334155",
                // New granular color properties with smart defaults
                header_icon_color: theme.dark.header_icon_color || theme.dark.header_text_color || "#e2e8f0",
                send_btn_color: theme.dark.send_btn_color || theme.dark.accent_color || "#0a766c",
                send_btn_icon_color: theme.dark.send_btn_icon_color || "#ffffff",
                input_placeholder_color: theme.dark.input_placeholder_color || "#64748b",
                timestamp_color: theme.dark.timestamp_color || "#64748b",
                search_highlight_color: theme.dark.search_highlight_color || "#ca8a04",
                loading_indicator_color: theme.dark.loading_indicator_color || theme.dark.accent_color || "#0a766c",
                footer_text_color: theme.dark.footer_text_color || "#64748b",
                success_color: theme.dark.success_color || "#4ade80",
                header_logo_border_color: theme.dark.header_logo_border_color || theme.dark.ai_bubble_border_color || "#334155",
                header_logo_bg_color: theme.dark.header_logo_bg_color || theme.dark.bg_color || "#020817",
                welcome_text_color: theme.dark.welcome_text_color || "#94a3b8",
                suggested_prompt_title_color: theme.dark.suggested_prompt_title_color || "#e2e8f0",
                suggested_prompt_desc_color: theme.dark.suggested_prompt_desc_color || "#94a3b8",
                suggested_prompt_icon_color: theme.dark.suggested_prompt_icon_color || "#94a3b8",
            },
            msg_bubble_radius: theme.msg_bubble_radius ?? 12,
            input_radius: theme.input_radius ?? 12,
            header_logo_radius: theme.header_logo_radius ?? 8,
            header_logo_width: theme.header_logo_width ?? 36,
            header_logo_height: theme.header_logo_height ?? 36,
            header_logo_border_width: theme.header_logo_border_width ?? 0,
            shadow_intensity: theme.shadow_intensity || "sm",
            loading_animation_style: theme.loading_animation_style || "dot",
            show_header_separator: theme.show_header_separator ?? false,
        };
    }

    // Migration logic for old flat structure
    return {
        light: {
            bg_color: theme.bg_color || "#ffffff",
            ai_bubble_color: theme.ai_bubble_color || "#ffffff",
            user_bubble_color: theme.user_bubble_color || "#0a766c",
            user_profile_bg_color: theme.user_profile_bg_color || "#0a766c",
            ai_profile_bg_color: theme.ai_profile_bg_color || "#0a766c",
            accent_color: theme.accent_color || "#0a766c",
            text_field_color: theme.text_field_color || "#ffffff",
            text_field_foreground: theme.text_field_foreground || "#0f172a",
            text_field_icon_color: theme.text_field_icon_color || theme.text_field_foreground || "#0f172a",
            footer_bg_color: theme.footer_bg_color || "#f8fafc",
            header_color: theme.header_color || "#ffffff",
            header_text_color: theme.header_text_color || "#0f172a",
            ai_bubble_text_color: theme.ai_bubble_text_color || "#0f172a",
            user_bubble_text_color: theme.user_bubble_text_color || "#ffffff",
            ai_bubble_border_color: theme.ai_bubble_border_color || "#e2e8f0",
            user_bubble_border_color: theme.user_bubble_border_color || "#e2e8f0",
            header_separator_color: theme.header_separator_color || "#e2e8f0",
            // New granular color properties
            header_icon_color: theme.header_text_color || "#0f172a",
            send_btn_color: theme.accent_color || "#0a766c",
            send_btn_icon_color: "#ffffff",
            input_placeholder_color: "#94a3b8",
            timestamp_color: "#94a3b8",
            search_highlight_color: "#fef08a",
            loading_indicator_color: theme.accent_color || "#0a766c",
            footer_text_color: "#94a3b8",
            success_color: "#22c55e",
            header_logo_border_color: theme.ai_bubble_border_color || "#e2e8f0",
            header_logo_bg_color: theme.bg_color || "#ffffff",
            welcome_text_color: "#64748b",
            suggested_prompt_title_color: "#0f172a",
            suggested_prompt_desc_color: "#64748b",
            suggested_prompt_icon_color: "#64748b",
        },
        dark: {
            bg_color: theme.dark_bg_color || "#020817",
            ai_bubble_color: theme.dark_ai_bubble_color || "#1e293b",
            user_bubble_color: theme.dark_user_bubble_color || "#0a766c",
            user_profile_bg_color: theme.dark_user_profile_bg_color || "#0a766c",
            ai_profile_bg_color: theme.dark_ai_profile_bg_color || "#0a766c",
            accent_color: theme.dark_accent_color || "#0a766c",
            text_field_color: theme.dark_text_field_color || "#1e293b",
            text_field_foreground: theme.dark_text_field_foreground || "#e2e8f0",
            text_field_icon_color: theme.dark_text_field_icon_color || theme.dark_text_field_foreground || "#e2e8f0",
            footer_bg_color: theme.dark_footer_bg_color || "#0f172a",
            header_color: theme.dark_header_color || "#020817",
            header_text_color: theme.dark_header_text_color || "#e2e8f0",
            ai_bubble_text_color: theme.dark_ai_bubble_text_color || "#e2e8f0",
            user_bubble_text_color: theme.dark_user_bubble_text_color || "#ffffff",
            ai_bubble_border_color: theme.dark_ai_bubble_border_color || "#334155",
            user_bubble_border_color: theme.dark_user_bubble_border_color || "#334155",
            header_separator_color: theme.dark_header_separator_color || "#334155",
            // New granular color properties
            header_icon_color: theme.dark_header_text_color || "#e2e8f0",
            send_btn_color: theme.dark_accent_color || "#0a766c",
            send_btn_icon_color: "#ffffff",
            input_placeholder_color: "#64748b",
            timestamp_color: "#64748b",
            search_highlight_color: "#ca8a04",
            loading_indicator_color: theme.dark_accent_color || "#0a766c",
            footer_text_color: "#64748b",
            success_color: "#4ade80",
            header_logo_border_color: theme.dark_ai_bubble_border_color || "#334155",
            header_logo_bg_color: theme.dark_bg_color || "#020817",
            welcome_text_color: "#94a3b8",
            suggested_prompt_title_color: "#e2e8f0",
            suggested_prompt_desc_color: "#94a3b8",
            suggested_prompt_icon_color: "#94a3b8",
        },
        msg_bubble_radius: theme.msg_bubble_radius ?? 12,
        input_radius: theme.input_radius ?? 12,
        header_logo_radius: theme.header_logo_radius ?? 8,
        header_logo_width: theme.header_logo_width ?? 36,
        header_logo_height: theme.header_logo_height ?? 36,
        header_logo_border_width: theme.header_logo_border_width ?? 0,
        shadow_intensity: theme.shadow_intensity || "sm",
        loading_animation_style: theme.loading_animation_style || "dot",
        show_header_separator: theme.show_header_separator ?? false,
    };
};

